### ISSUE TITLE
Missing zero in control/mod.rs?

### ISSUE THREAD

**Issue by C0rneille** [Smithay/drm-rs#106]
I think there's a zero missing in [src/control/mod.rs line 868](https://github.com/Smithay/drm-rs/blob/develop/src/control/mod.rs#L868): 

```
vblank_event.tv_usec * 100,
                       ^^^
```

**Comment by Drakulix** [comment]
Can you make a PR to fix it?

**Comment by C0rneille** [comment]
Yay! My first PR. Am I a real programmer now? 🤩
