### ISSUE TITLE
Atomic mode setting compatibility with libdrm

### ISSUE THREAD

**Issue by bjorn3** [Smithay/drm-rs#116]
I'm trying to create bindings to https://gitlab.freedesktop.org/emersion/libliftoff which uses libdrm and use it in a project that uses drm-rs. Unfortunately `AtomicModeReq` is not compatible with `drmModeAtomicReq` from `xf86drmMode.h`, nor is there any other type compatible with it. This means I can't commit the atomic mode setting request created by libliftoff.

**Comment by Drakulix** [comment]
drm-rs is not a wrapper around libdrm, but does ioctls itself directly to the kernel.

As a direct result of that, we cannot really and don't want to be data-compatible to libdrm.

What you need are some real bindings to libdrm. drm-rs is more strictly speaking a re-implementation of libdrm. Another potentially viable alternative (given its a rather small library) would be to re-implement libliftoff in Rust using drm-rs instead.

But libliftoff and drm-rs will never just work together.

**Comment by bjorn3** [comment]
I see. I will think a bit about which path to take.
