### ISSUE TITLE
Expose drm_sys::drm_clip_rect in the main crate

### ISSUE THREAD

**Issue by notgull** [Smithay/drm-rs#155]
This is used in the `dirty_framebuffer` function but isn't exposed in the main `drm` crate, necessitating the import of `drm-sys`.

**Comment by Drakulix** [comment]
Feel free to open a PR.

**Comment by notgull** [comment]
> Feel free to open a PR.

Okay, once #156 is merged I'll open a PR, since I don't want to expose `libc` in the public API of `drm-rs`.
