### ISSUE TITLE
Consider replacing drm-sys with linux-raw-sys

### ISSUE THREAD

**Issue by notgull** [Smithay/drm-rs#198]
See https://github.com/sunfishcode/linux-raw-sys/issues/123

**Comment by Slabity** [comment]
I mentioned this on that thread, but basically I don't mind deprecating the generated bindings in favor of a general-purpose UAPI crate. That would probably make it easier to maintain, especially for the huge number of architectures that exist.

Only concerns I have are what scope of the DRM subsystem is planned to be included there, and if this will still allow the crate to be used in non-Linux based systems.

**Comment by ids1024** [comment]
Yeah, `linux-raw-sys` isn't meant to be used on non-Linux systems, so I'm not sure it can replace drm-sys on BSDs?

**Comment by Drakulix** [comment]
> Yeah, `linux-raw-sys` isn't meant to be used on non-Linux systems, so I'm not sure it can replace drm-sys on BSDs?

I wonder if there is much point in doing this, if we still need to keep `drm-sys` around for BSDs then.

**Comment by notgull** [comment]
Ah, that's a good point.

**Comment by ids1024** [comment]
Yeah. And we're already using `rustix` for ioctls (so it won't need to go through libc on Linux, for what difference that makes), while `drm-rs` is just bindings for structs and constants. And we already have a working solution for generating those bindings.
