### ISSUE TITLE
Handling VblankEvent and PageFlipEvent

### ISSUE THREAD

**Issue by joone** [Smithay/drm-rs#27]
Hi, I'm trying to test VblankEvent and PageFlipEvent:
https://github.com/Smithay/drm-rs/blob/master/src/control/crtc.rs#L192

Is this working now? If so, is there any example for this?
This event handling was removed from the master branch. Is there any plan for replacing this code?

**Comment by joone** [comment]
Here is an example: https://github.com/Smithay/drm-rs/pull/28. PTAL.

**Comment by Slabity** [comment]
Looks like a good example to me. I'll merge it in
