### ISSUE TITLE
Looking to contributing / Roadmap?

### ISSUE THREAD

**Issue by Drakulix** [Smithay/drm-rs#3]
Hey there,
as I am currently trying to develop a drm backend for [smithay](https://github.com/Smithay/smithay) and I am in need of a working drm library I am looking into contributing to this library.

Do you have some kind of roadmap what still needs to be done? It currently seems to be lacking quite a bit functionality, I immediately did run into problems trying to find something like `drmHandleEvent` and I expect more to be missing, but this looks the most promising of all of them.

I do not have very deep knowledge about libdrm, so some hints on whats easy to do and some references would be nice.

Thanks for you work,
Drakulix

**Comment by Slabity** [comment]
Hey @Drakulix, I would definitely appreciate the help!

The end goal of this crate is to support all the features that the DRM API exposes, and act as a full replacement to mesa's libdrm. I do not have a concrete roadmap, but right now I'd like to get legacy modesetting (as in non-atomic) features working. You can use https://cgit.freedesktop.org/mesa/drm/tree/xf86drmMode.c as a guide of functions to be provided and how libdrm implements them. This is a rough state of how the crate is right now in terms of libdrm's functions:

Basic resources:
- [X] drmModeGetResources
- [X] drmModeGetConnector
- [X] drmModeGetEncoder
- [X] drmModeGetCrtc
- [X] drmModeSetCrtc
- [ ] drmModeCrtcGetGamma
- [ ] drmModeCrtcSetGamma
- [X] drmModeGetFB
- [ ] drmModeAddFB
- [ ] drmModeAddFB2
- [ ] drmModeAddFB2WithModifiers
- [ ] drmModeRmFB
- [ ] drmModeDirtyFB
- [ ] drmModeConnectorSetProperty (Not sure if this is necessary with below property functions)

Plane and cursor resources:
- [X] drmModeGetPlaneResources
- [X] drmModeGetPlane
- [ ] drmModeSetPlane
- [ ] drmModeSetCursor
- [ ] drmModeSetCursor2
- [ ] drmModeMoveCursor

Properties (mostly for atomic-modesetting):
- [X] drmModeObjectGetProperties
- [X] drmModeGetProperty
- [ ] drmModeObjectSetProperty
- [ ] drmModeGetPropertyBlob

Page flipping:
- [ ] drmModePageFlip
- [ ] drmModePageFlipTarget
- [ ] drmHandleEvent (usually page flipping)

Currently, legacy modesetting works (with drmModeSetCrtc), creating framebuffers from GEM buffers work, and I have also just finished dumb buffer creation and mapping. With those, you can *technically* get it to work as a backend for more complex rendering programs.

I also apologize for the multiple refactors. I'm still learning new (mostly undocumented) things about the DRM API that require different implementations.

**Comment by Drakulix** [comment]
Thanks! This looks like I can just start with some of the easier functions to get a hang of it, once you have written that README and then focus on the stuff, I need.

I will wait, no need to rush anything.

**Comment by Slabity** [comment]
I've added documentation to most of the `control` module and a readme with some very basic instructions. I'll go into more depth soon.

**Comment by Drakulix** [comment]
Finally got some. I added some questions to my first PR #4 .
Let me know what you think @Slabity  :)

**Comment by Slabity** [comment]
Looks good to me. I've cleaned up my warnings and test file a bit. Hopefully the `legacy_modeset` test is descriptive enough to refer to.

**Comment by Slabity** [comment]
Closing in favor of tracking #25
