### ISSUE TITLE
Continuous integration using Github Actions

### ISSUE THREAD

**Issue by katyo** [Smithay/drm-rs#73]
How about adding some CI to this project (And also for other such as gbm.rs, input.rs, udev-rs and etc.)?

We can automate the following tasks using CI:

* Check code formatting rules
* Check code quality using clippy
* Check building on all supported platforms
* Generate bindings for supported platforms
* Create pull-requests for updating generated bindings
* Publish crates when pushing version tag

The example how this works you can see in the following projects:

* [rquickjs](https://github.com/DelSkayn/rquickjs/actions/runs/545126260)
* [oboe-rs](https://github.com/katyo/oboe-rs/actions/runs/668871453)

**Comment by Drakulix** [comment]
Fixed with #74. Thanks again @katyo!

@Slabity I will leave this issue open, until you have setup the necessary repository secret for auto-publishing.
I cannot see, if the `CRATES_TOKEN` is already added to the repository. If it is, feel free to close this issue.

**Comment by Drakulix** [comment]
Added.
