### ISSUE TITLE
Is the main branch abandoned ?

### ISSUE THREAD

**Issue by NathanRoyer** [Smithay/drm-rs#76]
Hi ! Thank you for these crates, they are very useful for low level graphics management.
The `drm` crate as available to crates.io is pretty complete, but it lacks a feature or two that I would like to use in a project, related to cursor management. I see that these features have actually been implemented, but on the develop branch only.
Is anything preventing the crate update ?

**Comment by Drakulix** [comment]
The changes on the develop branch were re-writing a lot of the old code.
We plan to release a first version of that work on crates.io soon, but it took some time to iron out the new api.
Some PRs are still in the pipeline, after that a new release will likely happen. :)

**Comment by NathanRoyer** [comment]
Okay, thank you very much :D
